# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitbucket-mcp" do
  version "0.17.4"

  on_macos do
    on_intel do
      sha256 "a57732c30f00fe342d1e8c0c9882c670da3173e45ac49b5f4cdcb69c274d90d5"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "641519c2b0ef5313349edc20c8413f97f7311bcc8e0465a0e1dc349694556f78"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1da99044d8f1902cd31c9c53778c277bae8c9c4d023af6ad497ce66bf21d758c"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c35d783823bd25e128868a8035834e9752ee48f37443cde904da496c4f9794c"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitbucket-mcp"
  desc "An MCP server for interacting with Bitbucket via AI agents."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb-mcp"

  # No zap stanza required

end
