# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitbucket-mcp" do
  version "0.15.4"

  on_macos do
    on_intel do
      sha256 "4b53303271ac06d37480c9c4224c8eebeb692252d6c0137ec32c16b195e14f28"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9accdcc47c28721ecd8a1c3eb4b5b99a8eb61dd83198a74b7588791644a630b2"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "39d7257ee404f3dc08a0ab86e6fd5dfad3ebc5915c64c78ac16bf2b45be98ce3"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "927be637135beef2dfc97e84c1023fc2cd0710b17ee64491fa699e6920db6c99"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitbucket-mcp"
  desc "An MCP server for interacting with Bitbucket via AI agents."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb-mcp"

  # No zap stanza required

end
