# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitbucket-cli" do
  version "0.15.2"

  on_macos do
    on_intel do
      sha256 "a2ffba0a8c39e288e4dedaf251a1512cd5ea2dde538c493f8812c00a6e9dc244"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "390aa7fb0b6b19b899dcd0984588d60fc6ef9661d66d79c5adbce98509258d49"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ae8950b53aac0a803d6f2bf85ec0d9546d962086f6014d80057bd6787bc0023"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "43cce7e138e8acecbe195f9041c26d537f2e145f5bcbee8674f1522ab478a3ff"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitbucket-cli"
  desc "A CLI tool for interacting with Bitbucket."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb-cli"

  # No zap stanza required

end
