# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitbucket-mcp" do
  version "0.15.6"

  on_macos do
    on_intel do
      sha256 "ce9fe63a8f7ebd6d69f4ec3fc9170a231651324eb48478ee5c2abff60088f22b"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bda3ea208d7ff6806d16afa42f9956a14cebae451a48fae7a11d9ef151c30c9c"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92c6be7e002705b4c3a0ecf5a1aa8b2df026e1aa39a8b6f7d60ed448ea5d8e47"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44d8f396248a58b2ba64be4d0e2522bd97399a4cb934c0673015fe772277497a"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitbucket-mcp"
  desc "An MCP server for interacting with Bitbucket via AI agents."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb-mcp"

  # No zap stanza required

end
