# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitbucket-cli" do
  version "0.17.4"

  on_macos do
    on_intel do
      sha256 "96e018cbba86a9e07f52a8b82e5e1ee4d0221c1d37fd582489cc7cdb2d6bba73"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d0a01c0763c6ac508bf6eef86f51761c3f604119abe00d6e773231190bc31f7"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f21d4bbc7007c7bc9f25d79674e65d6c0182b96b1187fbee121e3ff26a847350"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fade040b3e67963fba56ea820ed344a21c859c76924b1cde4f6b44369a02063a"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitbucket-cli"
  desc "A CLI tool for interacting with Bitbucket."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb-cli"

  # No zap stanza required

end
