# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitbucket-cli" do
  version "0.15.3"

  on_macos do
    on_intel do
      sha256 "6ad46c39e4f12b0fc23fd49bf9f407b78fbf01e331087e001647b182bd9e21cc"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "769186c916e6e5199c9917d593522c06ced289b22419be1c07604e437797fdb6"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ee6035eee4f5e30cc67eb738f4a1613ab99b0f4620ab816afbde0485dec0894"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8cbd9d1d864d1a0005004f62b5788628cf2c9e1ff125bb1442ecd231d7d6736b"
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v#{version}/bb-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitbucket-cli"
  desc "A CLI tool for interacting with Bitbucket."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb-cli"

  # No zap stanza required

end
