# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketMcp < Formula
  desc "An MCP server for interacting with Bitbucket via AI agents."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"
  version "0.20.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.20.0/bb-mcp_0.20.0_darwin_amd64.tar.gz"
      sha256 "003cd224506e173a336c5a483389dc2677e7214ed3c68af3987f5829fc1841d6"

      define_method(:install) do
        bin.install "bb-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.20.0/bb-mcp_0.20.0_darwin_arm64.tar.gz"
      sha256 "92925bbb8963cdaef5f5afd0f159310da74bead961fd9331db3d13fd533bb406"

      define_method(:install) do
        bin.install "bb-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.20.0/bb-mcp_0.20.0_linux_amd64.tar.gz"
      sha256 "2a5bdc527480f9269ae5e501fc6627bcbba074f85d63e175884a94132974382d"
      define_method(:install) do
        bin.install "bb-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.20.0/bb-mcp_0.20.0_linux_arm64.tar.gz"
      sha256 "ce6105182170462328417cbe4477adef4de12e672f9e4876835898cc3b510c29"
      define_method(:install) do
        bin.install "bb-mcp"
      end
    end
  end

  test do
    assert_match "stdio", shell_output("#{bin}/bb-mcp --help", 2)
  end
end
