# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketCli < Formula
  desc "A CLI tool for interacting with Bitbucket."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"
  version "0.19.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.19.0/bb-cli_0.19.0_darwin_amd64.tar.gz"
      sha256 "9fa385b8ae5381b80daa80c66102545a179b6d0cd4d287970c0dd3ee74802e15"

      define_method(:install) do
        bin.install "bb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.19.0/bb-cli_0.19.0_darwin_arm64.tar.gz"
      sha256 "62c7f612fcafa2619ea93fc98cc507bfbabe410b9f769ccf15e4482db0348098"

      define_method(:install) do
        bin.install "bb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.19.0/bb-cli_0.19.0_linux_amd64.tar.gz"
      sha256 "a5111f900eb045cbe1544a179793a14f6f9d66699b6f53019904de837423146a"
      define_method(:install) do
        bin.install "bb-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.19.0/bb-cli_0.19.0_linux_arm64.tar.gz"
      sha256 "631bd79dd2b8243479f2022563e696a7c94d05e8b19951f663a08f287039b85b"
      define_method(:install) do
        bin.install "bb-cli"
      end
    end
  end

  test do
    system "#{bin}/bb-cli", "--version"
  end
end
