# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketCli < Formula
  desc "A CLI tool for interacting with Bitbucket."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"
  version "0.20.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.20.0/bb-cli_0.20.0_darwin_amd64.tar.gz"
      sha256 "1a36b6ac885d5ba468f2aee0bbcacea8b5430bc9f8ab857060129d08b1c279fb"

      define_method(:install) do
        bin.install "bb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.20.0/bb-cli_0.20.0_darwin_arm64.tar.gz"
      sha256 "4ea92aa158fac4b262ebe6e97744d45f0d20e0d6f5a72049dc7ac889e2c729f1"

      define_method(:install) do
        bin.install "bb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.20.0/bb-cli_0.20.0_linux_amd64.tar.gz"
      sha256 "a0a5b15f1de6b178838a2687a5628de96862df5ff230b6adf4e1ddd1f55b392d"
      define_method(:install) do
        bin.install "bb-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.20.0/bb-cli_0.20.0_linux_arm64.tar.gz"
      sha256 "45dfd8fea5958804904ee43bd70de5152cbdb9b1cbc646ed74192746f787595f"
      define_method(:install) do
        bin.install "bb-cli"
      end
    end
  end

  test do
    system "#{bin}/bb-cli", "--version"
  end
end
