# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketCli < Formula
  desc "A CLI tool for interacting with Bitbucket."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"
  version "0.18.5"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.18.5/bb-cli_0.18.5_darwin_amd64.tar.gz"
      sha256 "1f67425a7ccef0917f286975c46a398e0cdba6df81729fde4bdf3423a254d665"

      define_method(:install) do
        bin.install "bb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.18.5/bb-cli_0.18.5_darwin_arm64.tar.gz"
      sha256 "fb9855c882bac83ed7a3e7cd20829df7b267e5338aa665c72b85492e857440d7"

      define_method(:install) do
        bin.install "bb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.18.5/bb-cli_0.18.5_linux_amd64.tar.gz"
      sha256 "d9b130b36c98a07f566903f5906eec711e19def34f7d771beeb75ed26d3cdc88"
      define_method(:install) do
        bin.install "bb-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.18.5/bb-cli_0.18.5_linux_arm64.tar.gz"
      sha256 "1edcd5e3185f8a53535dadc07ea57e0dccf5eb34c1272c93c03f39fcbc73f417"
      define_method(:install) do
        bin.install "bb-cli"
      end
    end
  end

  test do
    system "#{bin}/bb-cli", "--version"
  end
end
