# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketMcp < Formula
  desc "An MCP server for interacting with Bitbucket via AI agents."
  homepage "https://github.com/FabianSchurig/bitbucket-cli"
  version "0.18.5"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.18.5/bb-mcp_0.18.5_darwin_amd64.tar.gz"
      sha256 "4a05460b2103701b924d6e5261a6581b150c4b4e70612d14fe0bd16b020a8765"

      define_method(:install) do
        bin.install "bb-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.18.5/bb-mcp_0.18.5_darwin_arm64.tar.gz"
      sha256 "51dc34f490c505241b2fe07788bf931d51f3175e6ebbcb40e2ba7d4227af2c88"

      define_method(:install) do
        bin.install "bb-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.18.5/bb-mcp_0.18.5_linux_amd64.tar.gz"
      sha256 "a1a2e39dba66d9f7154167ad305af20e86b4567a9e550cf7dcc4fca40473c1e5"
      define_method(:install) do
        bin.install "bb-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FabianSchurig/bitbucket-cli/releases/download/v0.18.5/bb-mcp_0.18.5_linux_arm64.tar.gz"
      sha256 "72efd41755c3c5c4719627fdc7117266da065b26bb39ab699eb5248ca14e55a9"
      define_method(:install) do
        bin.install "bb-mcp"
      end
    end
  end

  test do
    assert_match "stdio", shell_output("#{bin}/bb-mcp --help", 2)
  end
end
